In [5]:
import os 
import matplotlib.pyplot as plt 
import joblib 
import numpy as np 
import pandas as pd 

plt.style.use("fivethirtyeight")

In [ ]:
class Perceptron:
    ''' This class implements the perceptron for XOR Gate '''
    def __init__(self,eta:float=None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta #Learning Rate
        self.epochs = epochs 

    def fit(self, X,y):
        self.X = X 
        self.y = y

        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
        print(f'X with bias: \n{X_with_bias}')


In [17]:
obj = Perceptron(eta=0.01,epochs=10)

' This class implements the perceptron '

In [19]:
X = np.ones((4,2))
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [20]:
y = np.ones((4,1))

In [21]:
obj.fit(X,y)

X with bias: 
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]
