In [5]:
import os 
import matplotlib.pyplot as plt 
import joblib 
import numpy as np 
import pandas as pd 

plt.style.use("fivethirtyeight")

In [78]:
class Perceptron:
    ''' This class implements the perceptron for XOR Gate '''
    def __init__(self,eta:float=None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta #Learning Rate
        self.epochs = epochs 


    def _z_outcome(self, inputs, weights):
        return np.dot(inputs,weights)
    
    def activation_function(self, z):
        return np.where(z>0,1,0)
    
    def fit(self, X,y):
        self.X = X 
        self.y = y

        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
        print(f'X with bias: \n{X_with_bias}')

        for epoch in range(self.epochs):
            print("--"*10)
            print(f'for epochs >>  {epoch}')
            print("--"*10)
            z = self._z_outcome(X_with_bias,self.weights)
            y_hat = self.activation_function(z)
            print(f'Predicted value after forward pass:\n{y_hat}')

            self.error = self.y - y_hat 
            print(f'error: \n{self.error}')


        
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T,self.error)
            print(f"updated weights after epoch: {epoch +1 }/{self.epochs}: \n{self.weights}")
            print(f'##'*10)

    def predict(self,X):
        X_with_bias = np.c_[X, -np.ones((len(X),1))]
        print(len(X))
        z = self._z_outcome(X_with_bias,self.weights)
        return self.activation_function(z)



In [79]:
OR = {
    "x1":[0,0,1,1],
    "x2":[0,1,0,1],
    "y" :[0,1,1,1]

}
df_OR = pd.DataFrame(OR)
df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [80]:
def prepare_data(df,target_col="y"):
    X = df.drop(target_col,axis=1)
    y = df[target_col]
    return  X, y

In [81]:
X,y = prepare_data(df_OR)

ETA = 0.1
EPOCHS = 10

model_or = Perceptron(eta=ETA , epochs= EPOCHS)
model_or.fit(X,y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epochs >>  0
--------------------
Predicted value after forward pass:
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[1.54358040e-04 3.43003926e-05 9.99685998e-02]
####################
--------------------
for epochs >>  1
--------------------
Predicted value after forward pass:
[0 0 0 0]
error: 
0    0
1    1
2    1
3    1
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[ 0.20015436  0.2000343  -0.2000314 ]
####################
--------------------
for epochs >>  2
--------------------
Predicted value after forward pass:
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[ 0.20015436  0.2000343  -0.1000314 ]
####################
--------------------
for epochs >>  3
--------------------
Predicted value after forward pass:
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
N

In [82]:
model_or.predict([[0,0],[1,1]])

2


array([0, 1])

In [83]:
AND = {
    "x1":[0,0,1,1],
    "x2":[0,1,0,1],
    "y" :[0,0,0,1]

}
df_AND = pd.DataFrame(AND)
df_AND

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [84]:
def prepare_data(df,target_col="y"):
    X = df.drop(target_col,axis=1)
    y = df[target_col]
    return  X, y

In [85]:
X,y = prepare_data(df_AND)

ETA = 0.1
EPOCHS = 10

model_and = Perceptron(eta=ETA , epochs= EPOCHS)
model_and.fit(X,y) 

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epochs >>  0
--------------------
Predicted value after forward pass:
[1 1 1 1]
error: 
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[-0.09996189 -0.10006825  0.29991112]
####################
--------------------
for epochs >>  1
--------------------
Predicted value after forward pass:
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[ 3.81052018e-05 -6.82512570e-05  1.99911120e-01]
####################
--------------------
for epochs >>  2
--------------------
Predicted value after forward pass:
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[0.10003811 0.09993175 0.09991112]
####################
--------------------
for epochs >>  3
--------------------
Predicted value after forward pass:
[0 1 1 1]
error: 
0    0
1   -1
2   -1
3    0
N

In [87]:
XOR = {
    "x1":[0,0,1,1],
    "x2":[0,1,0,1],
    "y" :[0,1,1,0]

}
df_XOR = pd.DataFrame(XOR)
df_XOR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0

In [88]:
X,y = prepare_data(df_XOR)

ETA = 0.1
EPOCHS = 10

model_xor = Perceptron(eta=ETA , epochs= EPOCHS)
model_xor.fit(X,y) 

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epochs >>  0
--------------------
Predicted value after forward pass:
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[ 0.10009573  0.09996419 -0.19990201]
####################
--------------------
for epochs >>  1
--------------------
Predicted value after forward pass:
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[ 9.57314534e-05 -3.58059658e-05  9.79865000e-05]
####################
--------------------
for epochs >>  2
--------------------
Predicted value after forward pass:
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[ 0.10009573  0.09996419 -0.19990201]
####################
--------------------
for epochs >>  3
--------------------
Predicted value after forward pass:
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -